INSERT INTO Categories (CategoryName, Description) VALUES
('Telefon', 'Cep telefonları kategorisi'),
('Bilgisayar', 'Bilgisayar ve dizüstü bilgisayarlar'),
('Tablet', 'Tablet cihazları'),
('Kozmetik', 'Makyaj ve güzellik ürünleri'),
('Kitap', 'Kitaplar ve edebiyat'),
('Müzik', 'Müzik enstrümanları ve kayıtları'),
('Spor', 'Spor ekipmanları ve aktiviteleri'),
('Ev ve Bahçe', 'Ev dekorasyonu ve bahçe ürünleri'),
('Moda', 'Giyim ve modaya dair ürünler'),
('Oyuncak', 'Çocuk oyuncakları'),
('Hediye', 'Hediye fikirleri ve ürünleri'),
('Yiyecek ve İçecek', 'Gıda ve içecek ürünleri'),
('Sağlık ve Bakım', 'Sağlık ürünleri ve kişisel bakım'),
('Aksesuar', 'Takı ve aksesuarlar'),
('Film ve TV', 'Film ve televizyon ürünleri'),
('Ev Elektroniği', 'Ev elektroniği cihazları'),
('Bebek Ürünleri', 'Bebek bakım ürünleri'),
('Ofis Malzemeleri', 'Ofis malzemeleri ve mobilyaları'),
('Oto Aksesuarları', 'Oto aksesuarları ve yedek parçaları'),
('Hobi', 'Hobi ve el işleri ürünleri'),
('Seyahat', 'Seyahat ekipmanları ve valizler'),
('Ev Temizlik', 'Ev temizlik ürünleri'),
('Mücevher', 'Mücevherat ve kıymetli taşlar'),
('Giyim', 'Erkek ve kadın giyim ürünleri'),
('Giyim Aksesuarları', 'Giyim aksesuarları ve ayakkabılar'),
('Saç Bakım', 'Saç bakım ürünleri ve aksesuarları'),
('Cilt Bakım', 'Cilt bakım ürünleri ve kremleri'),
('Parfüm', 'Parfüm ve kokular'),
('Gözlük', 'Güneş gözlükleri ve optik çerçeveler'),
('Saat', 'Saatler ve aksesuarları'),
('Ayakkabı', 'Erkek ve kadın ayakkabıları'),
('Spor Ayakkabıları', 'Spor ayakkabıları'),
('Outdoor', 'Açık hava ve kamplama ekipmanları'),
('Spor Giyim', 'Spor giyim ürünleri'),
('Fitness', 'Fitness ekipmanları ve aksesuarları'),
('Bisiklet', 'Bisikletler ve aksesuarları'),
('Motosiklet', 'Motosiklet ekipmanları'),
('Elektrikli Ev Aletleri', 'Elektrikli ev aletleri'),
('Gıda Takviyeleri', 'Sporcu gıdaları ve takviyeleri'),
('Mutfak Gereçleri', 'Mutfak gereçleri ve aletleri'),
('Mobilya', 'Mobilya ve ev dekorasyonu'),
('Bahçe', 'Bahçe mobilyaları ve dekorasyonu'),
('Ev Tekstili', 'Ev tekstili ürünleri'),
('Yatak ve Yorgan', 'Yatak ve yorgan ürünleri'),
('Banyo', 'Banyo ürünleri ve aksesuarları');